no.nav.security.jwt:
  issuer.aad:
    discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
    accepted_audience:
      - ${AZURE_APP_CLIENT_ID}
      - "99862a5d-72f4-4286-8e58-458a9ff1f964"

management:
  endpoints:
    metrics:
      enabled: true
    web:
      exposure:
        include: info, health, metrics, prometheus
    export:
      prometheus:
        enabled: true
    prometheus:
      enabled: true
