kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: popp-testdata
  namespace: pensjonopptjening
  labels:
    team: pensjonopptjening
spec:
  azure:
    application:
      enabled: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev-gcp
    - name: popp_url_q1
      value: https://pensjon-popp-q1.nais.preprod.local/popp/api
    - name: popp_url_q2
      value: https://pensjon-popp-q2.nais.preprod.local/popp/api
    - name: POPP_Q1_API_ID
      value: dev-fss.pensjonopptjening.pensjon-popp-q1
    - name: POPP_Q2_API_ID
      value: dev-fss.pensjonopptjening.pensjon-popp-q2
  image: {{ image }}
  ingresses:
    - https://popp-testdata.dev.intern.nav.no
  liveness:
    path: /internal/isalive
    port: 8080
    initialDelay: 40
  readiness:
    path: /internal/isready
    port: 8080
    initialDelay: 40
  prometheus:
    enabled: true
    path: /actuator/prometheus
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "4"
      memory: 8096Mi
    requests:
      cpu: 400m
      memory: 4024Mi