kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: popp-testdata
  namespace: pensjonopptjening
  labels:
    team: pensjonopptjening
spec:
  azure:
    application:
      enabled: true
  kafka:
    pool: nav-dev
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev-gcp
    - name: popp.url.q1
      value: https://pensjon-popp-q1.nais.preprod.local/popp/api
    - name: popp.url.q2
      value: https://pensjon-popp-q2.nais.preprod.local/popp/api
  image: {{ image }}
  ingresses:
    - https://popp-testdata.dev.intern.nav.no
  liveness:
    path: /internal/isalive
    port: 8080
    initialDelay: 40
  readiness:
    path: /internal/isready
    port: 8080
    initialDelay: 40
  prometheus:
    enabled: true
    path: /actuator/prometheus
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "4"
      memory: 8096Mi
    requests:
      cpu: 400m
      memory: 4024Mi