name: Bygg og deploy popp-testdata til dev-gcp

on:
  push:
    branches:
      - main
jobs:
  tag_build_and_deploy:
    name: 'Build, deploy and tag'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: 'Pull repo'
        uses: actions/checkout@v4

      - name: 'Setter dato og commit variabel'
        run: |
          export TZ=CET
          echo "DATE=$(date "+%Y-%m-%d--%H-%M-%S")" >> $GITHUB_ENV
          echo "COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: 'Setting Image Variabel'
        run: echo "IMAGE=docker.pkg.github.com/${{ github.repository }}/popp-testdata:${{ env.DATE }}---${{ env.COMMIT_HASH }}" >> $GITHUB_ENV

      - name: 'Setting Image ghcr Variabel'
        run: echo "IMAGE_GHCR=ghcr.io/${{ github.repository }}/popp-testdata:${{ env.DATE }}---${{ env.COMMIT_HASH }}" >> $GITHUB_ENV

      - name: 'Java 21'
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
          java-package: jdk
          cache: 'gradle'

      - name: 'Bygg og publiser docker image'
        run: |
          ./gradlew build
          docker build --tag ${{ env.IMAGE }} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${{ secrets.GITHUB_TOKEN }}
          docker push ${{ env.IMAGE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Deploy popp-testdata to dev-gcp'
        uses: nais/deploy/actions/deploy@v2
        env:
          RESOURCE: nais/dev-gcp.yml
          CLUSTER: dev-gcp
          IMAGE: ${{ env.IMAGE_GHCR }}
