name: Bygg og deploy popp-testdata til dev-gcp

on:
  push:
    branches:
      - main
jobs:
  tag_build_and_deploy:
    name: 'Build, deploy and tag'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: 'Pull repo'
        uses: actions/checkout@v4

      - name: 'Java 17'
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: 'Bygg applikasjon'
        run: |
          ./gradlew build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build and push docker image'
        uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: pensjonopptjening
          tag: '${{ github.sha }}'

      - name: 'Deploy popp-testdata to dev-gcp'
        uses: nais/deploy/actions/deploy@v2
        env:
          RESOURCE: nais/dev-gcp.yml
          CLUSTER: dev-gcp
          IMAGE: ${{ steps.docker-push.outputs.image }}
          TELEMETRY: ${{ steps.docker-push.outputs.telemetry }}